config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")

  # root "articles#index"
  # get "booking/:id", to: "bookings#show"
  delete "trucks/:id", to: "trucks#destroy", as: 'destroy_truck'
  get "trucks/:id/edit", to: "trucks#edit", as: 'edit_truck'
  patch "trucks/:id", to: "trucks#update"

  get 'trucks/:id/owner_show', to: 'trucks#owner_show', as: 'truck_owner_show'
  get 'trucks/search', to: 'trucks#search', as: 'search_trucks'
  get '/bookings/:booking_id/confirmation', to: 'bookings#confirmation', as: 'confirmation'
  get 'user/area', to: 'pages#user', as: 'user_area'


  # get 'trucks/search', to: 'trucks#search', as: 'search_trucks'
  # get '/bookings/:booking_id/confirmation', to: 'bookings#confirmation', as: 'confirmation'

  resources :trucks do
    resources :bookings, only: [:new, :create, :show]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :truck

  validates :start_date, comparison: { less_than: :end_date }

end

app/models/feature.rb
class Feature < ApplicationRecord
  has_and_belongs_to_many :trucks, join_table: :truck_feature
end

app/models/truck.rb
class Truck < ApplicationRecord
  has_many :bookings
  has_many :users, through: :bookings
  belongs_to :owner, class_name: "User", foreign_key: "owner_id"

  has_and_belongs_to_many :features, join_table: :truck_feature

  validates :name, presence: true
  validates :description, presence: true
  validates :daily_fee, presence: true, numericality: { only_float: true }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :bookings
  has_many :owned_trucks, class_name: 'Truck'
  has_many :trucks, through: :bookings

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :registration])

    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :authenticate_user!

  def new
    @truck = Truck.find(params[:truck_id])
    @booking = @truck.bookings.new(booking_params)
    num_days = (@booking.end_date - @booking.start_date).to_i
    @booking.total_cost = num_days * @truck.daily_fee
  end

  def show
    @booking = Booking.find(params[:id])
  end

  def index
    @truck = Truck.find(params[:truck_id])
    @bookings = @truck.bookings
  end

  def create
    user = current_user
    truck = Truck.find(params[:truck_id])
    @booking = Booking.new(truck: truck, start_date: params[:start_date], end_date: params[:end_date], total_cost: params[:total_cost], user: user)

    if @booking.save!
      redirect_to confirmation_path(@booking)
    else
      render 'trucks/show'
    end
  end

  def confirmation
    @booking = Booking.find(params[:booking_id])
  end

  private
  def booking_params
    params.require(:booking).permit(:truck_id, :start_date, :end_date, :total_cost)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def user
    @user = current_user
    @bookings = current_user.bookings
    @trucks = Truck.all
    @id = @user.id
    @rentals = []

    @trucks.each do |truck|
      if truck.owner_id == @id
        @rentals << truck
        @price = truck.daily_fee

      end
    end
    @rented = @rentals
  end
end

app/controllers/trucks_controller.rb
class TrucksController < ApplicationController
  before_action :authenticate_user!, only: [:create]

  def index
    @trucks = Truck.all
  end

  def show
    @truck = Truck.find(params[:id])
    @booking = Booking.new
  end

  def search
    @trucks = Truck.where(location: params[:location].downcase, daily_fee: params[:daily_fee])
    render "index", locals: { trucks: @trucks }
  end

  def new
    @truck = Truck.new
  end

  def create
    @user = current_user
    @truck = Truck.new(truck_params)
    @truck.owner = @user
    @truck.owner_first_name = @user.first_name
    @truck.owner_second_name = @user.last_name
    if @truck.save
      flash[:notice] = "HERE'S YOUR NEW LISTING!"
      redirect_to truck_path(@truck)
    else
      render :new
    end
  end

  def edit
    @truck = Truck.find(params[:id])
  end

  def update
    @truck = Truck.find(params[:id])
    @truck.update(truck_params)
    redirect_to truck_path(@truck)
  end

  def destroy
    @truck = Truck.find(params[:id])
    @truck.destroy
  end

  private
  def truck_params
    params.require(:truck).permit(:name, :description, :location, :daily_fee)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = current_user
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/confirmation.html.erb
<h1>BOOKING CONFIRMED!</h1>

<%= "Booking ID: #{@booking.id}"  %>
<br>
<br>
<%= "User Name: #{@booking.user.first_name}"  %>
<br>
<br>
<%= "User ID: #{@booking.user.id}"  %>
<br>
<br>
<%= "Truck Name: #{@booking.truck.name}" %>
<br>
<br>
<p>VIEW THIS BOOKING ON YOUR <%= link_to("USER AREA", user_area_path) %><p>

app/views/bookings/index.html.erb
<ul>
  <% @bookings.each do |booking| %>
    <li><%= booking.id %></li>
  <% end %>
</ul>

app/views/bookings/new.html.erb
<div class="bookingbody">
<div class="bookingcard">
<h1>Booking Summary</h1>
<div class="bookingdetail">
<div class="internalbook">
<p>Truck: <%= @booking.truck.name %></p>
<% id = @booking_truck_id %>
<p>Start Date: <%= @booking.start_date %></p>
<% start = @booking_start_date %>
<p>End Date: <%= @booking.end_date %></p>
<% start = @booking.end_date %>
<p>Total Price: <%= "£#{@booking.total_cost}" %>
<% price = @booking.total_cost %>
<%= button_to("CONFIRM BOOKING", truck_bookings_path(truck: @booking.truck, end_date: @booking.end_date, start_date: @booking.start_date, total_cost: @booking.total_cost), data: {turbo_method: :post}) %>
</div>
<br>
<br>
<p>NOT SURE IF THIS IS THE TRUCK FOR YOU? </p><%= link_to("VIEW MORE TRUCKS", trucks_path ) %>
<br>
<br>
</div>
</div>
</div>

app/views/bookings/show.html.erb
<h1>Booking Confirmation</h1>

<p>Truck: <%= @booking.truck.name %></p>
<p>Start Date: <%= @booking.start_date %></p>
<p>End Date: <%= @booking.end_date %></p>
<p>Total Price: <%= @booking.total_cost %>
<br>
<%= link_to "Back To Truck", truck_path(@booking.truck) %>
<br>
<%= link_to("HOME PAGE", root_path) %>
<br>
<%= link_to("VIEW MORE TRUCKS", trucks_path ) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MonsterBnb</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
<nav class="navbar-lewagon">
  <a class="nav-left" href="/">MonstAir BnB</a>

  <%= form_tag(search_trucks_path, method: "get") do %>
    <%= label_tag(:q, "Location:") %>
    <%= text_field_tag(:location) %>
    <%= label_tag(:q, "daily_fee:") %>
    <%= text_field_tag(:daily_fee) %>
    <%= submit_tag("Search") %>
  <% end %>

  <div class="nav-right">
     <%= render "shared/navbar" %>
  </div>


</nav>
  <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<body class=body>
  <div class="homepage">
    <h1 class="banner-title">Monst-AIR BnB</h1>
    <div class = "links">
      <h3 class="link"><%= link_to("VIEW ALL TRUCKS", trucks_path) %></h3>
      <h3 class="link"><%= link_to("RENT YOUR TRUCK", new_truck_path) %></h3>
    </div>
  </div>
    <script src="script.js"></script>
</body>

app/views/pages/user.html.erb
<body class="userbody">
  <div class="usercard">
    <h1 class="username"><%= "#{@user.first_name} #{@user.last_name}'s YARD" %></h1>
    <p class="userdetails"><%= link_to "CHANGE DETAILS", edit_user_registration_path, class: "editdetails" %>
     <div class="useractivity">
      <div class="bookingscard", id="item">
        <h2>YOUR BOOKINGS</h2>
        <% if @bookings.empty? %>
          <p>No Bookings Made Yet</p>
        <% else %>
          <% @bookings.each do |booking|  %>
        <div class="bookings" >
            <p><%= link_to("#{booking.truck.name}", truck_path(booking.truck.id), class: "truckname")%></p>
            <p><%= "Booking Made On: #{booking.created_at}" %></p>
            <p><%= "Total Price: £#{booking.total_cost}" %></p>
            <p><%= "Truck Owner: #{booking.truck.owner_id}" %></p>
            <p><%= "Booking Reference: #{booking.id}" %></p>
        </div>
          <% end %>
        <% end %>
      </div>
      <% if @rented.empty? %>
        <!-- Rentals are empty, do not render the card -->
      <% else %>
      <div class="rentalscard", id="item">
        <h2>YOUR RENTALS</h2>
        <% @rented.each do |rented_truck| %>
          <div class="rentals">
            <%= "Truck Name: #{rented_truck.name}" %>
            <br>
            <%= "Daily Rental: £#{rented_truck.daily_fee.to_i}" %>
            <br>
            <p><%= link_to("REMOVE", destroy_truck_path(rented_truck.id), data: {turbo_method: :delete} ) %></p>
            <br>
            <p><%= link_to("EDIT", edit_truck_path(rented_truck.id)) %></p>
          </div>
        <% end %>
      <% end %>
      </div>
    </div>
  </div>
</body>

app/views/shared/_navbar.html.erb
<div class="nav-c">
<p class="navbar-text float-right">
  <% if user_signed_in? %>
    Logged in as <strong><%= "#{current_user.first_name.capitalize} #{current_user.last_name.capitalize}" %></strong>
    <br>
    <%= link_to("User Area", user_area_path) %> |
    <%= link_to "Logout", destroy_user_session_path, data: {turbo_method: :delete}, class: "navbar-link"  %> |
    <%= link_to("HOME PAGE", root_path) %> |
    <%= link_to("VIEW ALL TRUCKS", trucks_path) %> |
    <%= link_to("RENT YOUR TRUCK", new_truck_path) %>
  <% else %>
    <%= link_to "Sign up", new_user_registration_path, class: "navbar-link"  %> |
    <%= link_to "Login", new_user_session_path, class: "navbar-link"  %>
  <% end %>
</p>
</div>

app/views/trucks/edit.html.erb
<body class="editbody">
  <div class="editcard">
    <h1>Edit Your Truck</h1>
    <div class="editdetails">
      <%= form_with model: @truck do |f| %>
        <div class="editformsection">
        <%= f.label :name %>
        <br>
        <%= f.text_field :name %>
        </div>
        <div class="editformsection">
        <%= f.label :daily_fee %>
        <br>
        <%= f.text_field :daily_fee %>
        </div>
        <div class="editformsection">
        <%= f.label :description %>
        <br>
        <%= f.text_field :description %>
        <br>
        </div>
        <br>
        <%= f.submit %>
      <% end %>
    </div>
  </div>
</body>

app/views/trucks/index.html.erb
<div class="pagebody everything">
  <div class="grid">
    <% @trucks = trucks if @trucks.nil? %>
    <% @trucks.each do |truck| %>
      <div class="index-grid-item">
        <div>
          <%= image_tag 'mj22_mjs2_20220116_sanantoniotx_kl_11488.jpg', class: 'card-img'%>
        </div>
        <div class="card-index-content">
          <div class="card-index-header">
            <h1><%= link_to("#{truck.name}", truck_path(truck)) %></h1>
            <div class=index-truck-details>
              <p>Owner: <%= "#{truck.owner.first_name} #{truck.owner.last_name}" %></p>
              <p>Daily Rental: <%= "£#{truck.daily_fee.to_i}" %></p>
            </div>
          </div>
          <div>
            <ul class="card-index-text">
              <% truck.features.each do |feature| %>
                  <%= "#{feature.description}" %>
                  <br>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/trucks/new.html.erb
<body class="rentalbody">
  <div class="rentalcard">
    <h1>Rent Your Truck</h1>
    <div class="rentaldetails">
      <%= form_with model: @truck do |f| %>
        <div class="rentalsformsection">
        <%= f.label :"What's Your Truck's Name?", class: "rentalspageformfield" %>
        <br>
        <%= f.text_field :name %>
        </div>
        <div class="rentalsformsection">
        <%= f.label :"Tell Us A Bit About Your Beast", class: "rentalspageformfield"  %>
        <br>
        <%= f.text_field :description %>
        </div>
        <div class="rentalsformsection">
        <%= f.label :"Location, Please" , class: "rentalspageformfield"%>
        <br>
        <%= f.text_field :location %>
        </div>
        <div class="rentalsformsection">
        <%= f.label :"How Much Are You Charging For Your Monsta?" , class: "rentalspageformfield"%>
        <br>
        <%= f.number_field :daily_fee %>
        </div>
        <%= f.submit %>
      <% end %>
    </div>
  </div>
</body>

app/views/trucks/owner_show.html.erb
<p>hello world</p>

<h1><%= @truck.name.upcase %></h1>
<br>
<h4><%= "Description"%></h4>
<p><%= "#{@truck.description}" %></p>
<h4><%="Daily Rental Cost" %></h4>
<p><%= "£#{@truck.daily_fee }"%></p>
<h4><%="location" %></h4>
<p><%= "#{@truck.location }"%></p>
<h4>Owner</h4>
<p><%= "#{@truck.owner.email }"%></p>

app/views/trucks/show.html.erb
<body class="userbody">
  <div class="usercard" style="width: 1086px;">

    <h1 class="username"><%= "#{@truck.name}" %></h1>
    <div>
        <%= form_with(model: [@truck, @booking], url: new_truck_booking_path(@truck), method: :get) do |form| %>
        <%= form.label :start_date %>
        <%= form.date_field :start_date %>
        <%= form.label :end_date %>
        <%= form.date_field :end_date %>
        <%= form.submit "BOOK THIS TRUCK" %>
        <% end %>
    </div>
     <div class="useractivity">
      <div class="bookingscard", id="item">
          <%= image_tag('mj22_mjs2_20220116_sanantoniotx_kl_11488.jpg', class: 'truck_image') %>
      </div>
      <div class="rentalscard", id="item">
        <h2>Truck Details</h2>
        <h4 class="letters"><%= "Owner"%></h4>
        <p class="card-text"><%= "#{@truck.owner_first_name} #{@truck.owner_second_name}" %></p>
        <hr class="card-line">
        <h4 class="letters"><%= "Description"%></h4>
        <p class="card-text"><%= "#{@truck.description}" %></p>
        <hr class="card-line">
        <h4 class="card-title"><%="Daily Rental Cost" %></h4>
        <p class="card-text"><%= "£#{@truck.daily_fee.to_i}"%></p>
        <hr class="card-line">
        <h4 class="card-title"><%="location" %></h4>
        <p class="card-text"><%= "#{@truck.location }"%></p>
      </div>
    </div>
  </div>
</body>

app/views/users/show.html.erb
<h1><%= @user.email %></h1>

<h2>Trucks you own</h2>
<% @user.trucks.each do |truck| %>
  <p><%= truck.name %></p>
<% end %>

<h2>Your Bookings</h2>
<% @user.bookings.each do |booking| %>
  <p><%= booking.truck.name %></p>
  <p><%= booking.start_date %></p>
  <p><%= booking.end_date %></p>
  <br>
<% end %>